/* eslint-disable prettier/prettier */
const Thai = [
    {
        id: 1,
        name: 'ก',
        latin: 'k',
        sound: 'thai1',
    },
    {
        id: 2,
        name: 'ข',
        latin: 'kʰ',
        sound: 'thai2',
    },
    {
        id: 3,
        name: 'ค',
        latin: 'kʰ',
        sound: 'thai3',
    },
    {
        id: 4,
        name: 'ง',
        latin: 'ŋ',
        sound: 'thai4',
    },
    {
        id: 5,
        name: 'จ',
        latin: 'ch',
        sound: 'thai5',
    },
    {
        id: 6,
        name: 'ฉ',
        latin: 'ch',
        sound: 'thai6',
    },
    {
        id: 7,
        name: 'ช',
        latin: 'ch',
        sound: 'thai7',
    },
    {
        id: 8,
        name: 'ซ',
        latin: 's',
        sound: 'thai8',
    },
    {
        id: 9,
        name: 'ฌ',
        latin: 'ch',
        sound: 'thai9',
    },
    {
        id: 10,
        name: 'ญ',
        latin: 'y / n',
        sound: 'thai10',
    },
    {
        id: 11,
        name: 'ฎ',
        latin: 'd / t',
        sound: 'thai11',
    },
    {
        id: 12,
        name: 'ฏ',
        latin: 't',
        sound: 'thai12',
    },
    {
        id: 13,
        name: 'ฐ',
        latin: 'th / t',
        sound: 'thai13',
    },
    {
        id: 14,
        name: 'ฑ',
        latin: 'th / d / t',
        sound: 'thai14',
    },
    {
        id: 15,
        name: 'ฒ',
        latin: 'th / t',
        sound: 'thai15',
    },
    {
        id: 16,
        name: 'ณ',
        latin: 'n',
        sound: 'thai16',
    },
    {
        id: 17,
        name: 'ด',
        latin: 'd / t',
        sound: 'thai17',
    },
    {
        id: 18,
        name: 'ต',
        latin: 't',
        sound: 'thai18',
    },
    {
        id: 19,
        name: 'ถ',
        latin: 'th / t',
        sound: 'thai19',
    },
    {
        id: 20,
        name: 'ท',
        latin: 'th / t',
        sound: 'thai20',
    },
    {
        id: 21,
        name: 'ธ',
        latin: 'th / t',
        sound: 'thai21',
    },
    {
        id: 22,
        name: 'น',
        latin: 'n',
        sound: 'thai22',
    },
    {
        id: 23,
        name: 'บ',
        latin: 'b / p',
        sound: 'thai23',
    },
    {
        id: 24,
        name: 'ป',
        latin: 'p',
        sound: 'thai24',
    },
    {
        id: 25,
        name: 'ผ',
        latin: 'ph',
        sound: 'thai25',
    },
    {
        id: 26,
        name: 'ฝ',
        latin: 'f',
        sound: 'thai26',
    },
    {
        id: 27,
        name: 'พ',
        latin: 'ph / p',
        sound: 'thai27',
    },
    {
        id: 28,
        name: 'ฟ',
        latin: 'f / p',
        sound: 'thai28',
    },
    {
        id: 29,
        name: 'ภ',
        latin: 'ph / p',
        sound: 'thai29',
    },
    {
        id: 30,
        name: 'ม',
        latin: 'm',
        sound: 'thai30',
    },
    {
        id: 31,
        name: 'ย',
        latin: 'y / n',
        sound: 'thai31',
    },
    {
        id: 32,
        name: 'ร',
        latin: 'r / n',
        sound: 'thai32',
    },
    {
        id: 33,
        name: 'ล',
        latin: 'l / n',
        sound: 'thai33',
    },
    {
        id: 34,
        name: 'ว',
        latin: 'w',
        sound: 'thai34',
    },
    {
        id: 35,
        name: 'ศ',
        latin: 's / t',
        sound: 'thai35',
    },
    {
        id: 36,
        name: 'ษ',
        latin: 's / t',
        sound: 'thai36',
    },
    {
        id: 37,
        name: 'ส',
        latin: 's / t',
        sound: 'thai37',
    },
    {
        id: 38,
        name: 'ห',
        latin: 'h',
        sound: 'thai38',
    },
    {
        id: 39,
        name: 'ฬ',
        latin: 'l / n',
        sound: 'thai39',
    },
    {
        id: 40,
        name: 'อ',
        latin: '–',
        sound: 'thai40',
    },
    {
        id: 41,
        name: 'ฮ',
        latin: 'h',
        sound: 'thai41',
    },
];

export default Thai;
